### PR TITLE
Feat functions api javascript lang snippet

### PR DESCRIPTION
**Pull request by RJ025**
## Description  
(A brief summary of the contribution and the problem it solves. Try to keep the description short and only include relevant details)

## Testing  
(Describe steps to test out and verify the changes.You can also include images or screenshots of the result for better understanding)

## Checklist  
- [x] Followed the [contribution guidelines](https://github.com/2002Bishwajeet/awesome-appwrite-snippets/blob/master/CONTRIBUTING.md)  
- [x] The code is commented properly to give appropriate context.

### CODE REVIEW

**Comment by RJ025** [comment]
@2002Bishwajeet  i created another PR please check it out

**Comment by 2002Bishwajeet** [comment]
Please resolve merge conflicts. Also I could you have not synced up with master. Please do that

**Comment by RJ025** [comment]
@2002Bishwajeet  could I cut a new branch .

**Comment by 2002Bishwajeet** [comment]
Should be fine with this branch, you have some merge conflicts, google how to merge the branch and resolve conflicts😉. If you still get stuck lemme know what's disturbing you. Also you could reach out to me on [appwrite discord server](https://appwrite.io/discord) and we will solve the issues there together😄

**Comment by RJ025** [comment]
i just did the changes but i dont know why PR was not created @2002Bishwajeet

**Pull request closed without merging**
